#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("blue.Resource", IsApplication=true)]

namespace blue
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int file = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int folder = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050019
			public const int Mouse1 = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int Mouse2 = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int blue = 2131034134;
			
			// aapt resource value: 0x7f050010
			public const int btnDown = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int btnLeft = 2131034127;
			
			// aapt resource value: 0x7f050011
			public const int btnRight = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int btnSpacebar = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int btnUp = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int btnfile = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int btnkey = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int btnm = 2131034119;
			
			// aapt resource value: 0x7f05000b
			public const int btnsend = 2131034123;
			
			// aapt resource value: 0x7f050015
			public const int buttonlayout = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int comment = 2131034132;
			
			// aapt resource value: 0x7f05000a
			public const int editText1 = 2131034122;
			
			// aapt resource value: 0x7f050004
			public const int file_list_fragment = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int file_picker_image = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int file_picker_text = 2131034118;
			
			// aapt resource value: 0x7f05000e
			public const int layout = 2131034126;
			
			// aapt resource value: 0x7f050018
			public const int linearLayout1 = 2131034136;
			
			// aapt resource value: 0x7f050002
			public const int newd = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int newdevice = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int paired = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int pairedlist = 2131034113;
			
			// aapt resource value: 0x7f05001b
			public const int temp1 = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int temp2 = 2131034140;
			
			// aapt resource value: 0x7f050012
			public const int textView1 = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int title = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int wifi = 2131034135;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int device = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int file_main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int file_picker_list_item = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int key = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int list = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int mouse = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
